export const SCENARIOS = {
  fantasy: {
    title: { en: "Medieval Fantasy", es: "Fantasía Medieval", uk: "Середньовічне Фентезі", ru: "Средневековое Фэнтези" },
    era: "medieval fantasy",
    inventory: {
      en: ["Iron Longsword", "Leather Armor", "Healing Salve (x2)"],
      es: ["Espada Larga de Hierro", "Armadura de Cuero", "Bálsamo Curativo (x2)"],
      uk: ["Залізний довгий меч", "Шкіряний обладунок", "Цілющий бальзам (x2)"],
      ru: ["Железный длинный меч", "Кожаный доспех", "Целебный бальзам (x2)"]
    },
    intro: {
      en: "You stand at the ancient stone gates of Oak Keep, lost in the mists of the Whispering Peaks. The wind carries the scent of damp pine and old rain. The sword in your hand feels heavy. Legend says a dark artifact is hidden beneath the citadel.",
      es: "Te encuentras ante las antiguas puertas de piedra de Fortaleza del Roble, perdida en las brumas de los Picos Susurrantes. El viento trae el olor a pino húmedo y lluvia vieja. La espada en tu mano se siente pesada. La leyenda dice que un oscuro artefacto se oculta bajo la ciudadela.",
      uk: "Ви стоїте біля стародавніх кам'яних воріт Дубової Фортеці, загубленої у туманах Шепочущих Піків. Вітер доносить запах сирої сосни та старого дощу. Меч у вашій руці здається важким. Легенда говорить, що під цитаделлю схований темний артефакт.",
      ru: "Вы стоите у древних каменных ворот Дубовой Крепости, затерянной в туманах Шепчущих Пиков. Ветер доносит запах сырой сосны и старого дождя. Меч в вашей руке кажется тяжелым. Легенда гласит, что под цитаделью скрыт темный артефакт."
    },
    defaultMemory: {
      en: "You are an adventurer exploring ancient ruins in search of artifacts.",
      es: "Eres un aventurero explorando ruinas antiguas en busca de artefactos.",
      uk: "Ви — мандрівник, що досліджує стародавні руїни в пошуках артефактів.",
      ru: "Вы — искатель приключений, исследующий древние руины в поисках артефактов."
    },
    defaultAuthorNote: {
      en: "Dark fantasy setting, immersive atmospheric prose, detailed world descriptions.",
      es: "Entorno de fantasía oscura, prosa atmosférica inmersiva, descripciones detalladas del mundo.",
      uk: "Похмуре фентезі, занурювальна атмосферна проза, детальні описи світу.",
      ru: "Мрачное фэнтези, глубокая атмосфера, подробные описания мира."
    }
  },
  cyberpunk: {
    title: { en: "Cyberpunk Netrunner", es: "Netrunner Cyberpunk", uk: "Кіберпанк Нетраннер", ru: "Киберпанк Нетраннер" },
    era: "cyberpunk",
    inventory: {
      en: ["Cyberdeck (MK-IV)", "Monofilament Whip", "Encrypted Datapad", "Stimpack"],
      es: ["Cibercubierta (MK-IV)", "Látigo de Monofilamento", "Datapad Cifrado", "Estimulante"],
      uk: ["Кібердека (MK-IV)", "Моноволоконний батіг", "Зашифрований датапад", "Стимулятор"],
      ru: ["Кибердека (MK-IV)", "Моноволоконный хлыст", "Зашифрованный датапад", "Стимулятор"]
    },
    intro: {
      en: "Neon rain shimmers on the wet asphalt of Sector 7, while holographic ads flicker overhead. You pull up your collar against the chemical smog. Your cyberdeck chimed 5 minutes ago — an anonymous client uploaded a contract to hack a corporate database.",
      es: "La lluvia de neón brilla en el asfalto mojado del Sector 7, mientras los anuncios holográficos parpadean. Subes tu cuello para protegerte del smog químico. Tu cibercubierta sonó hace 5 minutos: un cliente anónimo subió un contrato para hackear una base de datos corporativa.",
      uk: "Неоновий дощ блищить на мокрому асфальті Сектора 7, а над головою мерехтять голографічні вивіски. Ви піднімаєте комір, захищаючись від хімічного смогу. Ваша кібердека дзенкнула 5 хвилин тому — анонімний замовник завантажив контракт на злам корпоративної бази.",
      ru: "Неоновый дождь блестит на мокром асфальте Сектора 7, а над головой мерцают голографические вывески. Вы поднимаете воротник, защищаясь от химозного смога. Ваша кибердека звякнула 5 минут назад — анонимный заказчик загрузил контракт на взлом корпоративной базы."
    },
    defaultMemory: {
      en: "You are a skilled netrunner operating in the criminal underworld of a megacity.",
      es: "Eres un hábil netrunner operando en el submundo criminal de una megaciudad.",
      uk: "Ви — досвідчений нетранер, що діє у кримінальному підпіллі мегаполісу.",
      ru: "Вы — опытный нетраннер, действующий в криминальном подбрюшье мегаполиса."
    },
    defaultAuthorNote: {
      en: "Gritty cyberpunk noir, neon-lit streets, corporate conspiracies, hacking culture.",
      es: "Cyberpunk noir oscuro, calles iluminadas de neón, conspiraciones corporativas, cultura hacker.",
      uk: "Похмурий кіберпанк-нуар, вулиці в неоновому світлі, корпоративні змови, хакерська культура.",
      ru: "Грязный киберпанк-нуар, улицы в неоновом свете, корпоративные заговоры, хакерская культура."
    }
  },
  zombie: {
    title: { en: "Zombie Apocalypse", es: "Apocalipsis Zombie", uk: "Зомбі Апокаліпсис", ru: "Зомби Апокалипсис" },
    era: "modern post-apocalypse",
    inventory: {
      en: ["Machete", "Water Canteen", "Flashlight (low battery)", "Bandages"],
      es: ["Machete", "Cantimplora de Agua", "Linterna (batería baja)", "Vendas"],
      uk: ["Мачете", "Фляга з водою", "Ліхтарик (сідає батарея)", "Бинти"],
      ru: ["Мачете", "Фляга с водой", "Фонарик (садится батарея)", "Бинты"]
    },
    intro: {
      en: "The sirens fell silent months ago. You crouch behind a rusted minivan on 5th Avenue, peering into broken shop windows. Two walkers wander near an abandoned grocery store across the street. Supplies are running low.",
      es: "Las sirenas se силиaron hace meses. Te agachas detrás de una minivan oxidada en la Quinta Avenida, mirando a través de escaparates rotos. Dos caminantes vagan cerca de una tienda abandonada al otro lado de la calle. Los suministros se agotan.",
      uk: "Сирени затихли кілька місяців тому. Ви сидите на карточках за заржавілим мінівеном на 5-й авеню, вдивляючись у розбиті вітрини. Два ходока блукають біля покинутого гастроному через дорогу. Припаси на межі.",
      ru: "Сирены затихли несколько месяцев назад. Вы сидите на корточках за заржавевшим минивэном на 5-й авеню, всматриваясь в выбитые витрины. Два ходока бродят возле заброшенного гастронома через дорогу. Припасы на исходе."
    },
    defaultMemory: {
      en: "You are a survivor in a zombie-infected city, scavenging for food, medicine, and safe shelter.",
      es: "Eres un superviviente en una ciudad infectada de zombis, buscando comida, medicinas y refugio seguro.",
      uk: "Ви — вижилий у місті, захопленому зомбі, що шукає їжу, ліки та безпечне укриття.",
      ru: "Вы — выживший в заражённом зомби городе, ищете еду, лекарства и безопасное укрытие."
    },
    defaultAuthorNote: {
      en: "Tense survival horror, realistic scarcity, moral dilemmas, visceral danger.",
      es: "Horror de supervivencia tenso, escasez realista, dilemas morales, peligro visceral.",
      uk: "Напружений survival horror, реалістична нестача ресурсів, моральні дилеми, відчутна небезпека.",
      ru: "Напряжённый survival horror, реалистичная нехватка ресурсов, моральные дилеммы, ощутимая опасность."
    }
  },
  detective: {
    title: { en: "Noir Detective", es: "Detective Noir", uk: "Нуарний Детектив", ru: "Нуарный Детектив" },
    era: "1940s-noir detective",
    inventory: {
      en: [".38 Revolver", "Notepad & Pen", "Silver Lighter", "Trenchcoat"],
      es: ["Revólver .38", "Cuaderno y Bolígrafo", "Encendedor de Plata", "Gabardina"],
      uk: ["Револьвер .38", "Блокнот і ручка", "Срібна запальничка", "Плащ"],
      ru: ["Револьвер .38", "Блокнот и ручка", "Серебряная зажигалка", "Плащ"]
    },
    intro: {
      en: "Rain beats a steady rhythm against your office window. The wall clock shows two in the morning. You pour a glass of cheap bourbon when the silhouette of a man in a fedora appears on the frosted glass door.",
      es: "La lluvia golpea un ritmo constante contra la ventana de tu oficina. El reloj marca las dos de la mañana. Sirves un vaso de bourbon barato cuando la silueta de un hombre con sombrero aparece en la puerta de cristal esmerilado.",
      uk: "Дощ відбиває чіткий ритм по склу вашого кабінету. Годинник на стіні показує другу годину ночі. Ви наливаєте склянку дешевого бурбону, коли на матовому склі дверей з'являється силует чоловіка в капелюсі.",
      ru: "Дождь отбивает четкий ритм по стеклу вашего кабинета. Часы на стене показывают два часа ночи. Вы наливаете стакан дешевого бурбона, когда на матовом стекле двери появляется силует человека в шляпе."
    },
    defaultMemory: {
      en: "You are a hard-boiled private detective in 1940s noir city, investigating crimes and conspiracies.",
      es: "Eres un duro detective privado en la ciudad noir de los años 40, investigando crímenes y conspiraciones.",
      uk: "Ви — жорсткий приватний детектив у нуарному місті 1940-х, що розслідує злочини та змови.",
      ru: "Вы — жёсткий частный детектив в нуарном городе 1940-х, расследующий преступления и заговоры."
    },
    defaultAuthorNote: {
      en: "Classic 1940s noir atmosphere, cynical inner monologue, rain-soaked streets, moral ambiguity.",
      es: "Atmósfera noir clásica de los años 40, monólogo interior cínico, calles empapadas de lluvia, ambigüedad moral.",
      uk: "Класична нуарна атмосфера 1940-х, цинічний внутрішній монолог, промоклі вулиці, моральна неоднозначність.",
      ru: "Классическая нуарная атмосфера 1940-х, циничный внутренний монолог, промокшие улицы, моральная неоднозначность."
    }
  }
};

export const THEME_PRESETS = {
  dark: {
    bgBase: '#09090b',
    bgSurface: '#121215',
    bgElevated: '#1a1a1f',
    bgOverlay: '#222228',
    bgInput: '#16161b',
    textPrimary: '#e4e4e7',
    textSecondary: '#a1a1aa',
    textMuted: '#71717a',
    accentPrimary: '#10b981',
    accentSecondary: '#34d399',
    accentGradient: 'linear-gradient(135deg, #10b981, #34d399)'
  },
  emerald: {
    bgBase: '#041710',
    bgSurface: '#08271c',
    bgElevated: '#0d3829',
    bgOverlay: '#134a37',
    bgInput: '#092e21',
    textPrimary: '#ecfdf5',
    textSecondary: '#a7f3d0',
    textMuted: '#6ee7b7',
    accentPrimary: '#10b981',
    accentSecondary: '#34d399',
    accentGradient: 'linear-gradient(135deg, #10b981, #34d399)'
  },
  purple: {
    bgBase: '#0d0714',
    bgSurface: '#180e25',
    bgElevated: '#241537',
    bgOverlay: '#311d4b',
    bgInput: '#1e1130',
    textPrimary: '#f3e8ff',
    textSecondary: '#c084fc',
    textMuted: '#a855f7',
    accentPrimary: '#a855f7',
    accentSecondary: '#c084fc',
    accentGradient: 'linear-gradient(135deg, #a855f7, #c084fc)'
  },
  crimson: {
    bgBase: '#140505',
    bgSurface: '#240a0a',
    bgElevated: '#360f0f',
    bgOverlay: '#4a1515',
    bgInput: '#2b0c0c',
    textPrimary: '#fee2e2',
    textSecondary: '#fca5a5',
    textMuted: '#f87171',
    accentPrimary: '#ef4444',
    accentSecondary: '#f87171',
    accentGradient: 'linear-gradient(135deg, #ef4444, #f87171)'
  },
  amber: {
    bgBase: '#120c03',
    bgSurface: '#211606',
    bgElevated: '#302009',
    bgOverlay: '#422c0c',
    bgInput: '#261a07',
    textPrimary: '#fef3c7',
    textSecondary: '#fcd34d',
    textMuted: '#fbbf24',
    accentPrimary: '#f59e0b',
    accentSecondary: '#fbbf24',
    accentGradient: 'linear-gradient(135deg, #f59e0b, #fbbf24)'
  },
  light: {
    bgBase: '#fcfbf7',
    bgSurface: '#f5f2eb',
    bgElevated: '#e9e4d9',
    bgOverlay: '#ddd6c7',
    bgInput: '#ebe6da',
    textPrimary: '#1c1917',
    textSecondary: '#44403c',
    textMuted: '#78716c',
    accentPrimary: '#059669',
    accentSecondary: '#10b981',
    accentGradient: 'linear-gradient(135deg, #059669, #10b981)'
  }
};

export const I18N = {
  en: {
    appTitle: "OdAI",
    chatsTitle: "Your Adventures",
    newChatBtn: "New Adventure",
    settingsTitle: "AI & Connection Settings",
    saveBtn: "Save",
    backBtn: "Back",
    languageLabel: "Interface Language",
    selectLanguageLabel: "Choose Interface & Story Language:",
    aiProvidersTitle: "AI Providers (Select Active)",
    inventoryTitle: "Inventory & World Memory",
    inventoryItemsLabel: "Inventory Items",
    addItemPlaceholder: "Add item (e.g., Torch)...",
    addBtn: "Add",
    worldMemoryLabel: "World Memory",
    memoryPlaceholder: "Key facts for AI to remember...",
    writingStyleLabel: "Writing Style & Tone",
    authorNotePlaceholder: "e.g., Dark fantasy, immersive prose...",
    inputPlaceholder: "Type a message... *action* or (OOC note)",
    sendBtn: "Send",
    d20Btn: "d20: Auto",
    continueBtn: "Continue",
    undoBtn: "Undo",
    retryBtn: "Retry",
    eraseBtn: "Erase",
    realismGuard: "Realism Guard",
    casualModeLabel: "Casual Mode (Always Succeed)",
    changeScenario: "Change World",
    behaviorPresetLabel: "Master Behavior / Persona",
    behaviorClassic: "🎭 Classic DM (Balanced)",
    behaviorConcise: "⚡ Concise & No-Fluff (Direct)",
    behaviorStrict: "⚔️ Strict & Hardcore (Unforgiving)",
    behaviorRomantic: "💖 Romantic & Emotional (Sensual)",
    behaviorDark: "🌌 Dark & Grimdark (Gothic)",
    behaviorChaotic: "🌀 Chaotic & Wild (Unpredictable)",
    behaviorNoir: "🔎 Cynical Noir (Mystery)",
    masterName: "Dungeon Master",
    youName: "You",
    exportJson: "Export JSON",
    exportTxt: "Export Text",
    importBackup: "Import Backup",
    backupTitle: "Backup & Export",
    backupSub: "Save and restore game data",
    caiTitle: "Import Character from Character.AI / Card",
    caiPlaceholder: "Paste c.ai link (https://character.ai/chat/...)",
    caiBtn: "Import",
    caiFileBtn: "Load Card File (.json)",
    scenarioModalTitle: "Choose Your World",
    startCustomBtn: "Start Custom World",
    customPromptLabel: "Or enter custom starting prompt:",
    customPromptPlaceholder: "You wake up in a quiet tavern with no memory of how you got here...",
    aiCreatorTitle: "✨ Auto-Generate AI Bot by Title & Character",
    aiCreatorSub: "Enter franchise title and character name — AI will load plot lore, personality, and start an interactive story!",
    franchiseTitleLabel: "Franchise / Title:",
    charNameLabel: "Character Name:",
    starterScenarioLabel: "Starting Situation (Optional):",
    aiCreatorBtn: "✨ Generate & Start Bot",
    aiCreatorGenerating: "⚡ AI is studying franchise lore and building character personality...",
    aiCreatorError: "Please enter franchise title and character name!",
    pwaInstallBtn: "📲 Install App (PWA)",
    aiGenerating: "AI is creating continuation...",
    realismChecking: "Arbiter checking realism...",
    testConnectionBtn: "Test Connection",
    noMessages: "No chats yet. Tap + to start a new adventure!",
    messagesCount: "msgs",
    lastMsg: "Last:",
    scenFantasyTitle: "Medieval Fantasy",
    scenFantasyDesc: "Knights, ancient ruins, magic, and dark dungeons.",
    scenCyberpunkTitle: "Cyberpunk Netrunner",
    scenCyberpunkDesc: "Neon alleys, neural implants, and megacorporations.",
    scenZombieTitle: "Zombie Apocalypse",
    scenZombieDesc: "Scavenge supplies and fight off hordes of infected.",
    scenDetectiveTitle: "Noir Detective",
    scenDetectiveDesc: "Rainy streets, dark secrets, and investigations.",
    geminiSub: "Free (15 req/min), no PC or servers required",
    geminiKeyLabel: "Google Gemini API Key",
    getKeyHint: "Get free key",
    geminiModelLabel: "Gemini Model",
    geminiAutoOption: "Auto-select (Recommended — best working model)",
    openrouterSub: "Llama 3 70B, Claude 3.5, DeepSeek, Qwen",
    openrouterKeyLabel: "OpenRouter API Key",
    openrouterKeysHint: "OpenRouter Keys",
    openrouterModelLabel: "OpenRouter Model",
    openrouterFreeModelsHint: "Free Models",
    openrouterFreeOption: "Auto-select free model (openrouter/free)",
    g4fSub: "Connect to Python backend on PC or Cloud",
    serverUrlLabel: "Server Address (IP or URL)",
    serverUrlHint: "Enter computer IP address on Wi-Fi network or cloud server URL.",
    openaiSub: "Custom Base URL for any local LLMs (Ollama / LM Studio)",
    openaiBaseUrlLabel: "Base URL",
    apiKeyLabel: "API Key",
    modelLabel: "Model",
    groqSub: "500+ tokens/sec, free tier (Llama 3.3, DeepSeek R1)",
    groqKeyLabel: "Groq API Key",
    groqKeysHint: "Get Groq Key",
    groqModelLabel: "Groq Model",
    anthropicSub: "Claude 3.5 Sonnet, Claude 3.5 Haiku, Claude 3 Opus",
    anthropicKeyLabel: "Anthropic API Key",
    anthropicKeysHint: "Anthropic Keys",
    anthropicModelLabel: "Claude Model",
    builtinSub: "100% Offline operation without internet or servers",
    builtinDesc: "Uses local built-in RPG engine. Requires no internet, keys, or servers.",
    genSettingsHeader: "Generation Parameters & Testing",
    tempLabel: "Creativity (Temperature)",
    contextLengthLabel: "Memory Depth (Context)",
    settingsTitleBtn: "Settings",
    backToChatsTitle: "Back to chats",
    interactiveDM: "Interactive Dungeon Master",
    chatMenuTitle: "Chat Menu",
    themeLabel: "Theme & Appearance",
    selectThemeLabel: "Select Color Theme:",
    themeDefault: "Onyx Dark (Default)",
    themeEmerald: "Dark Emerald",
    themePurple: "Cyber Purple",
    themeCrimson: "Vampire Crimson",
    themeAmber: "Amber Terminal",
    themeLight: "Light Parchment",
    themeCustom: "Custom Colors...",
    customBgPrimary: "Main Background",
    customBgSurface: "Surface & Cards",
    customAccent: "Accent Color",
    customText: "Text Color"
  },
  es: {
    appTitle: "OdAI",
    chatsTitle: "Tus Aventuras",
    newChatBtn: "Nueva Aventura",
    settingsTitle: "Ajustes de IA y Conexión",
    saveBtn: "Guardar",
    backBtn: "Volver",
    languageLabel: "Idioma de la Interfaz",
    selectLanguageLabel: "Elige el idioma de la interfaz e historia:",
    aiProvidersTitle: "Proveedores de IA (Seleccionar Activo)",
    inventoryTitle: "Inventario y Memoria",
    inventoryItemsLabel: "Objetos en el Inventario",
    addItemPlaceholder: "Añadir objeto (ej. Antorcha)...",
    addBtn: "Añadir",
    worldMemoryLabel: "Memoria del Mundo",
    memoryPlaceholder: "Hechos clave que la IA debe recordar...",
    writingStyleLabel: "Estilo de Escritura y Tono",
    authorNotePlaceholder: "ej. Fantasía oscura, prosa inmersiva...",
    inputPlaceholder: "Escribe un mensaje... *acción* o (nota OOC)",
    sendBtn: "Enviar",
    d20Btn: "d20: Auto",
    continueBtn: "Continuar",
    undoBtn: "Deshacer",
    retryBtn: "Reintentar",
    eraseBtn: "Borrar",
    realismGuard: "Guardia de Realismo",
    casualModeLabel: "Modo Casual (Siempre Éxito)",
    changeScenario: "Cambiar Mundo",
    behaviorPresetLabel: "Modo de Comportamiento del DM",
    behaviorClassic: "🎭 DM Clásico (Equilibrado)",
    behaviorConcise: "⚡ Conciso y Directo (Sin Relleno)",
    behaviorStrict: "⚔️ Estricto y Hardcore (Sin Piedad)",
    behaviorRomantic: "💖 Romántico y Emocional (Sensual)",
    behaviorDark: "🌌 Fantasía Oscura (Gótico)",
    behaviorChaotic: "🌀 Caótico y Salvaje (Impredecible)",
    behaviorNoir: "🔎 Noir Cínico (Misterio)",
    masterName: "Dungeon Master",
    youName: "Tú",
    exportJson: "Exportar JSON",
    exportTxt: "Exportar Texto",
    importBackup: "Importar Copia",
    backupTitle: "Copia de Seguridad y Exportación",
    backupSub: "Guardar y restaurar datos del juego",
    caiTitle: "Importar Personaje de Character.AI / Tarjeta",
    caiPlaceholder: "Pega enlace c.ai (https://character.ai/chat/...)",
    caiBtn: "Importar",
    caiFileBtn: "Cargar Archivo de Tarjeta (.json)",
    scenarioModalTitle: "Elige Tu Mundo",
    startCustomBtn: "Iniciar Mundo Personalizado",
    customPromptLabel: "O escribe un mensaje de inicio personalizado:",
    customPromptPlaceholder: "Te despiertas en una taberna tranquila sin recordar cómo llegaste...",
    aiCreatorTitle: "✨ Auto-Generar Bot de IA por Título y Personaje",
    aiCreatorSub: "¡Ingresa el título de la franquicia y el nombre del personaje: la IA cargará el lore y comenzará la historia!",
    franchiseTitleLabel: "Franquicia / Título:",
    charNameLabel: "Nombre del Personaje:",
    starterScenarioLabel: "Situación Inicial (Opcional):",
    aiCreatorBtn: "✨ Generar y Empezar Bot",
    aiCreatorGenerating: "⚡ La IA está estudiando el lore y creando la personalidad...",
    aiCreatorError: "¡Ingresa el título y el nombre del personaje!",
    pwaInstallBtn: "📲 Instalar Aplicación (PWA)",
    aiGenerating: "La IA está creando la continuación...",
    realismChecking: "El Árbitro está verificando el realismo...",
    testConnectionBtn: "🧪 Probar Conexión",
    noMessages: "¡No hay chats aún. Toca + para empezar!",
    messagesCount: "mensajes",
    lastMsg: "Último:",
    scenFantasyTitle: "Fantasía Medieval",
    scenFantasyDesc: "Caballeros, ruinas antiguas, magia y mazmorras oscuras.",
    scenCyberpunkTitle: "Cyberpunk Netrunner",
    scenCyberpunkDesc: "Callejones de neón, implantes neurales y megacorporaciones.",
    scenZombieTitle: "Apocalipsis Zombi",
    scenZombieDesc: "Busca suministros y lucha contra hordas de infectados.",
    scenDetectiveTitle: "Detective Noir",
    scenDetectiveDesc: "Calles lluviosas, secretos oscuros e investigaciones.",
    geminiSub: "Gratis (15 req/min), sin PC ni servidores",
    geminiKeyLabel: "Clave API de Google Gemini",
    getKeyHint: "🔑 Obtener clave gratis",
    geminiModelLabel: "Modelo Gemini",
    geminiAutoOption: "🤖 Selección automática (Recomendado — mejor modelo funcional)",
    openrouterSub: "Llama 3 70B, Claude 3.5, DeepSeek, Qwen",
    openrouterKeyLabel: "Clave API de OpenRouter",
    openrouterKeysHint: "🔑 Claves de OpenRouter",
    openrouterModelLabel: "Modelo de OpenRouter",
    openrouterFreeModelsHint: "🎁 Modelos gratis",
    openrouterFreeOption: "🤖 Selección automática de modelo gratis (openrouter/free)",
    g4fSub: "Conectar al backend de Python en PC o Nube",
    serverUrlLabel: "Dirección del Servidor (IP o URL)",
    serverUrlHint: "Introduce la IP de la computadora en red Wi-Fi o URL del servidor en la nube.",
    openaiSub: "Base URL personalizada para cualquier IA local (Ollama / LM Studio)",
    openaiBaseUrlLabel: "Base URL (Punto final)",
    apiKeyLabel: "Clave API",
    modelLabel: "Modelo",
    groqSub: "500+ tokens/seg, nivel gratuito (Llama 3.3, DeepSeek R1)",
    groqKeyLabel: "Clave API de Groq",
    groqKeysHint: "🔑 Obtener clave de Groq",
    groqModelLabel: "Modelo Groq",
    anthropicSub: "Claude 3.5 Sonnet, Claude 3.5 Haiku, Claude 3 Opus",
    anthropicKeyLabel: "Clave API de Anthropic",
    anthropicKeysHint: "🔑 Claves de Anthropic",
    anthropicModelLabel: "Modelo Claude",
    builtinSub: "Funcionamiento 100% Offline sin internet ni servidores",
    builtinDesc: "📦 Utiliza el motor RPG local integrado. No requiere internet, claves ni servidores.",
    genSettingsHeader: "Parámetros de Generación y Pruebas",
    tempLabel: "Creatividad (Temperatura)",
    contextLengthLabel: "Profundidad de Memoria (Contexto)",
    settingsTitleBtn: "Ajustes",
    backToChatsTitle: "Volver a los chats",
    interactiveDM: "Dungeon Master Interactivo",
    chatMenuTitle: "Menú del chat",
    themeLabel: "Tema y Apariencia",
    selectThemeLabel: "Seleccionar Tema de Color:",
    themeDefault: "Onyx Oscuro (Predeterminado)",
    themeEmerald: "Esmeralda Oscuro",
    themePurple: "Púrpura Cíber",
    themeCrimson: "Carmesí Vampiro",
    themeAmber: "Terminal Ámbar",
    themeLight: "Pergamino Claro",
    themeCustom: "Colores Personalizados...",
    customBgPrimary: "Fondo Principal",
    customBgSurface: "Superficie y Tarjetas",
    customAccent: "Color de Acento",
    customText: "Color de Texto"
  },
  uk: {
    appTitle: "OdAI",
    chatsTitle: "Ваші Пригоди",
    newChatBtn: "Нова Пригода",
    settingsTitle: "Налаштування ШІ та З'єднань",
    saveBtn: "Зберегти",
    backBtn: "Назад",
    languageLabel: "Мова інтерфейсу",
    selectLanguageLabel: "Оберіть мову інтерфейсу та історії:",
    aiProvidersTitle: "Провайдери ШІ (Оберіть активний)",
    inventoryTitle: "Інвентар та Пам'ять",
    inventoryItemsLabel: "Предмети з собою",
    addItemPlaceholder: "Додати предмет (напр. Смолоскип)...",
    addBtn: "Додати",
    worldMemoryLabel: "Пам'ять світу",
    memoryPlaceholder: "Введіть ключові факти, які ШІ повинен пам'ятати...",
    writingStyleLabel: "Стиль написання та тон",
    authorNotePlaceholder: "Задайте стиль написання ШІ (напр. Похмуре фентезі)...",
    inputPlaceholder: "Напишіть повідомлення... *дія* або (уточнення)",
    sendBtn: "Надіслати",
    d20Btn: "d20: Авто",
    continueBtn: "Продовжити",
    undoBtn: "Скасувати",
    retryBtn: "Повторити",
    eraseBtn: "Стерти",
    realismGuard: "Захист Реалізму",
    casualModeLabel: "Казуальний Режим (Завжди Успіх)",
    changeScenario: "Змінити Світ",
    behaviorPresetLabel: "Модель поведінки Майстра",
    behaviorClassic: "🎭 Класичний Майстер (Баланс)",
    behaviorConcise: "⚡ Лаконічний та Без Води (Чіткий)",
    behaviorStrict: "⚔️ Строгий та Суровий (Хардкор)",
    behaviorRomantic: "💖 Романтичний та Чуттєвий (Емоції)",
    behaviorDark: "🌌 Похмуре Фентезі (Готика)",
    behaviorChaotic: "🌀 Хаотичний та Безумний (Драйв)",
    behaviorNoir: "🔎 Цинічний Нуар (Детектив)",
    masterName: "Майстер Гри",
    youName: "Ви",
    exportJson: "Експорт JSON",
    exportTxt: "Експорт Текст",
    importBackup: "Імпорт Бэкапу",
    backupTitle: "Резервне копіювання та Експорт",
    backupSub: "Збереження та відновлення даних гри",
    caiTitle: "Імпорт персонажа з Character.AI / Картки",
    caiPlaceholder: "Вставте посилання c.ai (https://character.ai/chat/...)",
    caiBtn: "Імпорт",
    caiFileBtn: "Завантажити Файл Картки (.json)",
    scenarioModalTitle: "Оберіть ваш світ",
    startCustomBtn: "Почати свій світ",
    customPromptLabel: "Або введіть свій стартовий промпт:",
    customPromptPlaceholder: "Ви прокидаєтеся у тихій таверні і не пам'ятаєте, як тут опинилися...",
    aiCreatorTitle: "✨ Авто-створення бота за Тайтлом та Іменем",
    aiCreatorSub: "Введіть назву франшизи та ім'я персонажа — ШІ підвантажить лор, сюжет, характер та запустить історію!",
    franchiseTitleLabel: "Франшиза / Тайтл:",
    charNameLabel: "Ім'я Персонажа:",
    starterScenarioLabel: "Стартова ситуація (Опціонально):",
    aiCreatorBtn: "✨ Згенерувати та Почати",
    aiCreatorGenerating: "⚡ ШІ вивчає лор тайтлу та генерує особистість персонажа...",
    aiCreatorError: "Вкажіть назву тайтлу та ім'я персонажа!",
    pwaInstallBtn: "📲 Встановити додаток (PWA)",
    aiGenerating: "ШІ створює продовження...",
    realismChecking: "Арбітр перевіряє реалізм...",
    testConnectionBtn: "🧪 Перевірити з'єднання",
    noMessages: "Чатів поки немає. Натисніть +, щоб почати!",
    messagesCount: "повідомл.",
    lastMsg: "Ост:",
    scenFantasyTitle: "Середньовічне Фентезі",
    scenFantasyDesc: "Лицарі, стародавні руїни, магія та похмурі підземелля.",
    scenCyberpunkTitle: "Кіберпанк Нетранер",
    scenCyberpunkDesc: "Неонові провулки, нейроімпланти та мегакорпорації.",
    scenZombieTitle: "Зомби Апокаліпсис",
    scenZombieDesc: "Шукайте припаси та боріться з ордами заражених.",
    scenDetectiveTitle: "Нуарний Детектив",
    scenDetectiveDesc: "Дощові вулиці, темні таємниці та розслідування.",
    geminiSub: "Безкоштовно (15 запр/хв), без ПК та серверів",
    geminiKeyLabel: "API Ключ Google Gemini",
    getKeyHint: "🔑 Отримати безкоштовний ключ",
    geminiModelLabel: "Модель Gemini",
    geminiAutoOption: "🤖 Авто-підбір (Рекомендовано — вибір кращої робочої моделі)",
    openrouterSub: "Llama 3 70B, Claude 3.5, DeepSeek, Qwen",
    openrouterKeyLabel: "API Ключ OpenRouter",
    openrouterKeysHint: "🔑 Ключі OpenRouter",
    openrouterModelLabel: "Модель OpenRouter",
    openrouterFreeModelsHint: "🎁 Безкоштовні моделі",
    openrouterFreeOption: "🤖 Авто-вибір безкоштовної моделі (openrouter/free)",
    g4fSub: "Підключення до Python бекенду на ПК або в хмарі",
    serverUrlLabel: "Адреса сервера (IP або URL)",
    serverUrlHint: "Укажіть IP комп'ютера у Wi-Fi мережі або адресу хмарного сервера.",
    openaiSub: "Кастомний Base URL для будь-яких локальних нейромереж (Ollama / LM Studio)",
    openaiBaseUrlLabel: "Base URL (Кінцева точка)",
    apiKeyLabel: "API Ключ",
    modelLabel: "Модель",
    groqSub: "500+ токенів/сек, безкоштовний тир (Llama 3.3, DeepSeek R1)",
    groqKeyLabel: "API Ключ Groq",
    groqKeysHint: "🔑 Отримати ключ Groq",
    groqModelLabel: "Модель Groq",
    anthropicSub: "Claude 3.5 Sonnet, Claude 3.5 Haiku, Claude 3 Opus",
    anthropicKeyLabel: "API Ключ Anthropic",
    anthropicKeysHint: "🔑 Ключі Anthropic",
    anthropicModelLabel: "Модель Claude",
    builtinSub: "100% Офлайн роботи без інтернету та серверів",
    builtinDesc: "📦 Використовується локальний вбудований RPG-двигун. Не потребує інтернету, ключів та серверів.",
    genSettingsHeader: "Параметри Генерації та Тестування",
    tempLabel: "Креативність (Temperature)",
    contextLengthLabel: "Глибина Пам'яті (Контекст)",
    settingsTitleBtn: "Налаштування",
    backToChatsTitle: "Назад до чатів",
    interactiveDM: "Інтерактивний D&D Ведучий",
    chatMenuTitle: "Меню чату",
    themeLabel: "Тема та Оформлення",
    selectThemeLabel: "Оберіть тему оформлення:",
    themeDefault: "Онікс Темна (За замовчуванням)",
    themeEmerald: "Темний Смарагд",
    themePurple: "Кібер Фіолетовий",
    themeCrimson: "Багряно-Червона",
    themeAmber: "Янтарний Термінал",
    themeLight: "Світлий Пергамент",
    themeCustom: "Свої Кольори...",
    customBgPrimary: "Основний Фон",
    customBgSurface: "Поверхні та Картки",
    customAccent: "Акцентний Колір",
    customText: "Колір Тексту"
  },
  ru: {
    appTitle: "OdAI",
    chatsTitle: "Ваши приключения",
    newChatBtn: "Новое приключение",
    settingsTitle: "Настройки ИИ и Подключений",
    saveBtn: "Сохранить",
    backBtn: "Назад",
    languageLabel: "Язык интерфейса",
    selectLanguageLabel: "Выберите язык интерфейса и истории:",
    aiProvidersTitle: "Провайдеры ИИ (Выберите активный)",
    inventoryTitle: "Инвентарь и Память",
    inventoryItemsLabel: "Предметы с собой",
    addItemPlaceholder: "Добавить предмет (напр. Факел)...",
    addBtn: "Добавить",
    worldMemoryLabel: "Память мира",
    memoryPlaceholder: "Введите ключевые факты, которые ИИ должен помнить...",
    writingStyleLabel: "Стиль написания и тон",
    authorNotePlaceholder: "Задайте стиль написания ИИ (напр. Мрачное фэнтези)...",
    inputPlaceholder: "Напишите сообщение... *действие* или (уточнение)",
    sendBtn: "Отправить",
    d20Btn: "d20: Авто",
    continueBtn: "Продолжить",
    undoBtn: "Отмена",
    retryBtn: "Повтор",
    eraseBtn: "Стереть",
    realismGuard: "Защита Реализма",
    casualModeLabel: "Казуальный Режим (Всегда Успех)",
    changeScenario: "Сменить мир",
    behaviorPresetLabel: "Модель поведения Мастера",
    behaviorClassic: "🎭 Классический Мастер (Баланс)",
    behaviorConcise: "⚡ Лаконичный и Без Воды (Четкий)",
    behaviorStrict: "⚔️ Строгий и Суровый (Хардкор)",
    behaviorRomantic: "💖 Романтик и Чувственный (Эмоции)",
    behaviorDark: "🌌 Мрачное Фэнтези (Готика)",
    behaviorChaotic: "🌀 Хаотичный и Безумный (Драйв)",
    behaviorNoir: "🔎 Циничный Нуар (Детектив)",
    masterName: "Мастер Игры",
    youName: "Вы",
    exportJson: "Экспорт JSON",
    exportTxt: "Экспорт Текст",
    importBackup: "Импорт Бэкапа",
    backupTitle: "Резервное копирование и Экспорт",
    backupSub: "Сохранение и восстановление данных игры",
    caiTitle: "Импорт персонажа из Character.AI / Карточки",
    caiPlaceholder: "Вставьте ссылку c.ai (https://character.ai/chat/...)",
    caiBtn: "Импорт",
    caiFileBtn: "Загрузить Файл Карточки (.json)",
    scenarioModalTitle: "Выберите ваш мир",
    startCustomBtn: "Начать свой мир",
    customPromptLabel: "Или введите свой стартовый промпт:",
    customPromptPlaceholder: "Вы просыпаетесь в тихой таверне и не помните, как здесь оказались...",
    aiCreatorTitle: "✨ Авто-создание бота по Тайтлу и Имени",
    aiCreatorSub: "Введите название франшизы и имя персонажа — ИИ подгрузит лор, сюжет, характер и запустит историю!",
    franchiseTitleLabel: "Франшиза / Тайтл:",
    charNameLabel: "Имя Персонажа:",
    starterScenarioLabel: "Стартовая ситуация (Опционально):",
    aiCreatorBtn: "✨ Сгенерировать и Начать",
    aiCreatorGenerating: "⚡ ИИ изучает лор тайтла и генерирует личность персонажа...",
    aiCreatorError: "Укажите название тайтла и имя персонажа!",
    pwaInstallBtn: "📲 Установить приложение (PWA)",
    aiGenerating: "ИИ создает продолжение...",
    realismChecking: "Арбитр проверяет реализм...",
    testConnectionBtn: "🧪 Проверить подключение",
    noMessages: "Чатов пока нет. Нажмите +, чтобы начать!",
    messagesCount: "сообщ.",
    lastMsg: "Посл:",
    scenFantasyTitle: "Средневековое Фэнтези",
    scenFantasyDesc: "Рыцари, древние руины, магия и мрачные подземелья.",
    scenCyberpunkTitle: "Киберпанк Нетраннер",
    scenCyberpunkDesc: "Неоновые переулки, нейроимпланты и мегакорпорации.",
    scenZombieTitle: "Зомби Апокалипсис",
    scenZombieDesc: "Добывайте припасы и сражайтесь с ордами зараженных.",
    scenDetectiveTitle: "Нуарный Детектив",
    scenDetectiveDesc: "Дождливые улицы, тёмные тайны и расследования.",
    geminiSub: "Бесплатно (15 запр/мин), без ПК и серверов",
    geminiKeyLabel: "API Ключ Google Gemini",
    getKeyHint: "🔑 Получить бесплатный ключ",
    geminiModelLabel: "Модель Gemini",
    geminiAutoOption: "🤖 Авто-подбор (Рекомендуется — выбор лучшей рабочей модели)",
    openrouterSub: "Llama 3 70B, Claude 3.5, DeepSeek, Qwen",
    openrouterKeyLabel: "API Ключ OpenRouter",
    openrouterKeysHint: "🔑 Ключи OpenRouter",
    openrouterModelLabel: "Модель OpenRouter",
    openrouterFreeModelsHint: "🎁 Бесплатные модели",
    openrouterFreeOption: "🤖 Авто-выбор свободной модели (openrouter/free)",
    g4fSub: "Подключение к Python бэкенду на ПК или в облаке",
    serverUrlLabel: "Адрес сервера (IP или URL)",
    serverUrlHint: "Укажите IP компьютера в Wi-Fi сети или адрес облачного сервера.",
    openaiSub: "Кастомный Base URL для любых локальных нейросетей (Ollama / LM Studio)",
    openaiBaseUrlLabel: "Base URL (Конечная точка)",
    apiKeyLabel: "API Ключ",
    modelLabel: "Модель",
    groqSub: "500+ токенов/сек, бесплатный тир (Llama 3.3, DeepSeek R1)",
    groqKeyLabel: "API Ключ Groq",
    groqKeysHint: "🔑 Получить ключ Groq",
    groqModelLabel: "Модель Groq",
    anthropicSub: "Claude 3.5 Sonnet, Claude 3.5 Haiku, Claude 3 Opus",
    anthropicKeyLabel: "API Ключ Anthropic",
    anthropicKeysHint: "🔑 Ключи Anthropic",
    anthropicModelLabel: "Модель Claude",
    builtinSub: "100% Офлайн работы без интернета и серверов",
    builtinDesc: "📦 Используется локальный встроенный RPG-движок. Не требует интернета, ключей и серверов.",
    genSettingsHeader: "Параметры Генерации и Тестирование",
    tempLabel: "Креативность (Temperature)",
    contextLengthLabel: "Глубина Памяти (Контекст)",
    settingsTitleBtn: "Настройки",
    backToChatsTitle: "Назад к чатам",
    interactiveDM: "Интерактивный D&D Ведущий",
    chatMenuTitle: "Меню чата"
  }
};
